name: CI

on: [push,pull_request]

jobs:
  build_test_lint:
    name: Test on ${{ matrix.os }} Node ${{ matrix.node_version }}

    strategy:
      matrix:
        node_version: [8, 10, 12]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn build
    - name: Test
      run: yarn test
    - name: Lint
      run: yarn lint
